apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  labels:
    app: blog
spec:
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: mparadowsky/blog
        env:
          - name: PGHOST
            valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: DATABASE_HOST
          - name: PGDATABASE
            valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: DATABASE_NAME
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: DATABASE_PASSWORD
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: DATABASE_USERNAME
        ports:
          - containerPort: 3000