apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  labels:
    app: blog
spec:
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: mparadowsky/blog
        env:
          - name: PGHOST
            valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: PGHOST
          - name: PGDATABASE
            valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: PGHOST
          - name: PGDATABASE
            valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: PGPASSWORD
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: PGUSER
        ports:
          - containerPort: 3000