apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  labels:
    app: blog
spec:
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: mparadowsky/blog
        env:
          - name: PGHOST
            value: database-service.default.svc.cluster.local
          - name: PGDATABASE
            value: blog_backend
          - name: PGPASSWORD
            value: blog_backend
          - name: PGUSER
            value: blog_backend
        ports:
          - containerPort: 3000