apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  labels:
    app: blog
spec:
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      imagePullSecrets:
      - name: registry-key
      containers:
      - name: blog
        image: 090660780783.dkr.ecr.eu-central-1.amazonaws.com/blog
        env:
          - name: DATABASE_HOST
            valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: DATABASE_HOST
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: DATABASE_NAME
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: DATABASE_PASSWORD
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: DATABASE_USERNAME
          - name: REDIS_URI
            valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: REDIS_URI
        ports:
          - containerPort: 3000