apiVersion: v1
kind: Service
metadata:
  name: database-svc
  labels:
    app: db
spec:
  type: ClusterIP
  clusterIP: 10.97.135.163
  selector:
    app: db
  ports:
   - protocol: TCP
     name: db-port
     port: 5432
     targetPort: 5432
