apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: db
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres
        env:
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: DATABASE_NAME
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: DATABASE_PASSWORD
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: DATABASE_USERNAME
        ports:
          - containerPort: 5432
    

        