apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: db
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres
        env:
          - name: POSTGRES_PASSWORD
            valueFrom: 
              name: dbsecret
              key: DATABASE_PASSWORD
          - name: POSTGRES_USER
            valueFrom: 
              name: dbsecret
              key: DATABASE_USERNAME
          - name: POSTGRES_DB
            valueFrom: 
              name: dbsecret
              key: DATABASE_NAME
        ports:
          - containerPort: 5432
    

        