apiVersion: v1
kind: Secret
metadata:
  name: dbsecrets
type: Opaque
stringData:
  PGHOST: "database-service.default.svc.cluster.local"
  PGDATABASE: "blog_backend"
  PGPASSWORD: "blog_backend"
  PGUSER: "blog_backend"
  POSTGRES_DB: "blog_backend"
  POSTGRES_PASSWORD: "blog_backend"
  POSTGRES_USER: "blog_backend"