apiVersion: v1
kind: Secret
metadata:
  name: dbsecrets
type: Opaque
stringData:
  DATABASE_HOST: "database-service.default.svc.cluster.local"
  DATABASE_NAME: "blog_backend"
  DATABASE_PASSWORD: "blog_backend"
  DATABASE_USERNAME: "blog_backend"
  REDIS_URI: "redis://redis:6379/0"