apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx
  # annotations:
  #   kubernetes.io/ingress.class: 'nginx'
spec:
  rules:
    - http:
        paths:
        - path: /
          backend:
            serviceName: blog-svc
            servicePort: 3000
