apiVersion: apps/v1
kind: Pod
metadata:
  name: blog
  labels:
    app: app2
specs:
  containers:
  - name: front-end
    image: blog
    ports:
      - containerPort: 3000
    env:
      - name: PGUSER
        value: blog_backend
      - name: PGHOST
        value: db
      - name: PGPASSWORD
        value: blog_backend
      - name: PGDATABASE
        value: blog_backend
  - name: db
    image: redis
    env:
      - name: POSTGRES_DB
        value: blog_backend
      - name: POSTGRES_PASSWORD
        value: blog_backend
      - name: POSTGRES_USER
        value: blog_backend
