version: '3'
services:
  db:
    image: 'postgres:latest'
    #env_file:
     # - .env
    environment:
      #- POSTGRES_DB=${DATABASE_NAME} 
      #- POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      #- POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_DB=blog_backend
      - POSTGRES_PASSWORD=blog_backend
      - POSTGRES_USER=blog_backend
  blog:
    build: .
    ports:
      - '3000:3000'
    #env_file:
     # - .env
    environment:
      #- PGDATABASE=${DATABASE_NAME} 
      #- PGPASSWORD=${DATABASE_PASSWORD}
      #- PGUSER=${DATABASE_USERNAME}
      #- PGHOST=${DATABASE_HOST}
      - PGDATABASE=blog_backend
      - PGPASSWORD=blog_backend
      - PGUSER=blog_backend
      - PGHOST=db