node() {
    def ver = sh (script: "git rev-parse --short HEAD | tr -d '\n'", returnStdout: true) 
    stage("Cloning repository") {
        git branch: 'dev', url: 'https://github.com/mparadowsky/devops-exercise'
    }
    dir("./blog/") {
    stage("Building image") {
        withEnv(['VERSION='+ver]) {
            sh 'docker-compose build blog' 
            sh 'docker-compose push blog'
        }
    }
    stage("Launching app") {
        withEnv(['VERSION='+ver]) {
          sh 'kubectl apply -f kubernetes'
        }
    }
}
}